/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "serial.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(McData, McData, AUTO)

PB_BIND(McParams, McParams, AUTO)

PB_BIND(McDataMsg, McDataMsg, AUTO)

PB_BIND(McParamsMsg, McParamsMsg, AUTO)
