/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SERIAL_PB_H_INCLUDED
#define PB_SERIAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SerialTxMessage {
    uint32_t v_bus;
    uint32_t curr_fdbk_a;
    uint32_t curr_fdbk_b;
    uint32_t curr_fdbk_c;
    uint32_t bemf_a;
    uint32_t bemf_b;
    uint32_t bemf_c;
    uint32_t output_pulse;
    uint32_t speed_fdbk;
    uint32_t direction;
} SerialTxMessage;

typedef struct _SerialRxMessage {
    uint32_t kp_gain;
    uint32_t ki_gain;
    uint32_t kd_gain;
    bool modulation_type;
    bool pid_status;
} SerialRxMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SerialTxMessage_init_default             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SerialRxMessage_init_default             {0, 0, 0, 0, 0}
#define SerialTxMessage_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SerialRxMessage_init_zero                {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SerialTxMessage_v_bus_tag                1
#define SerialTxMessage_curr_fdbk_a_tag          2
#define SerialTxMessage_curr_fdbk_b_tag          3
#define SerialTxMessage_curr_fdbk_c_tag          4
#define SerialTxMessage_bemf_a_tag               5
#define SerialTxMessage_bemf_b_tag               6
#define SerialTxMessage_bemf_c_tag               7
#define SerialTxMessage_output_pulse_tag         8
#define SerialTxMessage_speed_fdbk_tag           9
#define SerialTxMessage_direction_tag            10
#define SerialRxMessage_kp_gain_tag              1
#define SerialRxMessage_ki_gain_tag              2
#define SerialRxMessage_kd_gain_tag              3
#define SerialRxMessage_modulation_type_tag      4
#define SerialRxMessage_pid_status_tag           5

/* Struct field encoding specification for nanopb */
#define SerialTxMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   v_bus,             1) \
X(a, STATIC,   SINGULAR, UINT32,   curr_fdbk_a,       2) \
X(a, STATIC,   SINGULAR, UINT32,   curr_fdbk_b,       3) \
X(a, STATIC,   SINGULAR, UINT32,   curr_fdbk_c,       4) \
X(a, STATIC,   SINGULAR, UINT32,   bemf_a,            5) \
X(a, STATIC,   SINGULAR, UINT32,   bemf_b,            6) \
X(a, STATIC,   SINGULAR, UINT32,   bemf_c,            7) \
X(a, STATIC,   SINGULAR, UINT32,   output_pulse,      8) \
X(a, STATIC,   SINGULAR, UINT32,   speed_fdbk,        9) \
X(a, STATIC,   SINGULAR, UINT32,   direction,        10)
#define SerialTxMessage_CALLBACK NULL
#define SerialTxMessage_DEFAULT NULL

#define SerialRxMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   kp_gain,           1) \
X(a, STATIC,   SINGULAR, UINT32,   ki_gain,           2) \
X(a, STATIC,   SINGULAR, UINT32,   kd_gain,           3) \
X(a, STATIC,   SINGULAR, BOOL,     modulation_type,   4) \
X(a, STATIC,   SINGULAR, BOOL,     pid_status,        5)
#define SerialRxMessage_CALLBACK NULL
#define SerialRxMessage_DEFAULT NULL

extern const pb_msgdesc_t SerialTxMessage_msg;
extern const pb_msgdesc_t SerialRxMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SerialTxMessage_fields &SerialTxMessage_msg
#define SerialRxMessage_fields &SerialRxMessage_msg

/* Maximum encoded size of messages (where known) */
#define SERIAL_PB_H_MAX_SIZE                     SerialTxMessage_size
#define SerialRxMessage_size                     22
#define SerialTxMessage_size                     60

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
